name: Application
on:
  push:
    branches:
      - main
    paths:
      - application/**
      - .github/workflows/application.yml
jobs:
  deploy:
    environment: approval
    runs-on: ubuntu-latest
    env: 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
    - name: Checkout code
      id: checkout
      uses: actions/checkout@v3
    
    - name: Install requirements
      id: requirements
      run: sudo apt update && sudo apt install -y zip
    
    - name: Deploy App
      id: deploy
      run: make deploy_app