name: Application
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - application/**
      - .github/workflows/application.yml
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS Credentials
      id: creds
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Checkout code
      id: checkout
      uses: actions/checkout@v3
    
    - name: Install requirements
      id: requirements
      run: sudo apt update && sudo apt install -y zip
    
    - name: Deploy App
      id: deploy
      run: make deploy_app